window.FS_CONFIG = {
  BACKEND_URL: "https://script.google.com/macros/s/AKfycbzgeudLE5_yzFRQ4ejGE2_2aYwBIDSkxQRy2Ptj72b755Zy8ypvmcWlNR1cuLQRPKblpw/exec",
  ENABLED_QUESTION_IDS: ["S1Q01", "S1Q02"],
  QUESTION_IMAGE_DIR: "",
  ASSET_VERSION: "20260826-1220",
  GAME_MODE: "NONCONFORMITY",
  RANDOMIZE_QUESTIONS: false,
  AUTO_NEXT_SECONDS: 0,
  REMEMBER_EMAIL: true
};
